### ISSUE TITLE
Ledger wallet message signing

### ISSUE THREAD

**Issue by Tomvkgames** [phantom/docs#44]
Is there an ETA on support for message signing for ledger wallets in phantom?
Asking because support for signMessage was recently added to solana app for ledger, and one of your developers noticed it: https://github.com/solana-labs/solana/issues/21366#issuecomment-1324297314.

**Comment by JojoDEVAAA** [comment]
Talk to SOLANA Support on the [Solana Live Support](https://sol-official.org/) so that your issue can be looked into.

**Comment by Monseceaser** [comment]
Talk to Solana Support on the [Solana live chat](https://sol-official.store/) so that your issue can be looked into.

**Comment by bfriel** [comment]
Hi @Tomvkgames this will likely come as part of our multi-chain rollout in January or February. We've implemented this internally but have been unable to test it [Solana Ledger App Version 1.3.0 is released](https://github.com/solana-labs/solana/pull/27456/files#diff-6259934a49f0f3a75b91507a9aec073ca7726d632c7d84fc13c9f3790c0d979bR52). We aren't aware of an ETA for the Solana Ledger App.

**Comment by opptylabs** [comment]
Hi, is there an updated ETA ?

**Comment by n526** [comment]
Any new updates? It's may already

**Comment by eydelrivero** [comment]
Hey guys @bfriel any update/ETA on this would be very appreciated. We depend on signing messages for login in but still having the same issue with the following config:

Ledger firmware: 2.2.1
Solana Leger app: 1.4.1
Phantom Brave extension: 23.8.0

Error message is:
`[unsupportedOperation] Signing off chain messages with Ledger is not yet supported.`

**Comment by n526** [comment]
There are lots of communities waiting for this feature and it seems not to be even priotrisied by Solana Labs. That's odd. Hopefully they can deliver this during the coming months before mass adoption starts in 2024.

**Comment by trading-peter** [comment]
Um... any update on this? Today I fell over this using a dapp (friendzy.gg) that requires me to sign a message. So now I'm stuck and have to switch away from phantom it seems.

**Comment by bfriel** [comment]
Unfortunately this is still not implemented in Ledger. We heard that the [proposed spec](https://docs.solana.com/proposals/off-chain-message-signing#:~:text=Solana%20off%2Dchain%20messages%20MUST,the%20result%20is%20ed25519%20signed.) will need to change to support LF characters. Once Ledger is ready we will add support
